"""Initial

Revision ID: 9469b676d559
Revises:
Create Date: 2022-06-22 19:11:44.382634

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9469b676d559'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_unit',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('parentId', postgresql.UUID(), nullable=True),
        sa.Column('type', sa.Enum('OFFER', 'CATEGORY', name='shop_unit_type'), nullable=False),
        sa.Column('price', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk__shop_unit')),
    )
    op.create_index(op.f('ix__shop_unit__parentId'), 'shop_unit', ['parentId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__shop_unit__parentId'), table_name='shop_unit')
    op.drop_table('shop_unit')
    # ### end Alembic commands ###
